---
- name: "RULE 4.1.1.1 | Ensure auditd is installed (Automated)"
  apt:
      name: audispd-plugins
      state: present
      install_recommends: false
  when:
      - not ubuntu2004cis_skip_for_travis
      - ubuntu2004cis_rule_4_1_1_1
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.1.1

- name: "RULE 4.1.1.2 | Ensure auditd service is enabled (Automated)"
  service:
      name: auditd
      state: started
      enabled: true
  when:
      - not ubuntu2004cis_skip_for_travis
      - ubuntu2004cis_rule_4_1_1_2
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.1.2

- name: "RULE 4.1.1.3 | Ensure auditing for processes that start prior to auditd is enabled (Automated)"
  replace:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*audit)\"[^\"]*)(\".*)'
      replace: '\1 audit=1\2'
  notify:
      - generate new grub config
  when:
      - ubuntu2004cis_rule_4_1_1_3
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.1.3

- name: "RULE 4.1.1.4 | Ensure audit_backlog_limit is sufficient (Automated)"
  replace:
      dest: /etc/default/grub
      regexp: '^(GRUB_CMDLINE_LINUX=(?!.*audit_backlog_limit)\"[^\"]*)(\".*)'
      replace: '\1 audit_backlog_limit={{ ubuntu2004cis_auditd.backlog_limit }}\2'
  ignore_errors: true
  notify:
      - generate new grub config
  when:
      - ubuntu2004cis_rule_4_1_1_4
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.1.4

- name: "RULE 4.1.2.1 | Ensure audit log storage size is configured (Automated)"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file( |=)"
      line: "max_log_file = {{ ubuntu2004cis_auditd.max_audit_log_file_size }}"
      state: present
      create: yes
  when:
      - ubuntu2004cis_rule_4_1_2_1
  notify:
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.2.1

- name: "RULE 4.1.2.2 | Ensure audit logs are not automatically deleted (Automated)"
  lineinfile:
      dest: /etc/audit/auditd.conf
      regexp: "^max_log_file_action"
      line: "max_log_file_action = {{ ubuntu2004cis_auditd['max_log_file_action'] }}"
      state: present
      create: yes
  when:
      - ubuntu2004cis_rule_4_1_2_2
  notify:
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.2.2

- name: "RULE 4.1.2.3 | Ensure system is disabled when audit logs are full (Automated)"
  block:
      - name: "RULE 4.1.2.3 | Ensure system is disabled when audit logs are full | admin_space_left_action (Automated)"
        lineinfile:
            dest: /etc/audit/auditd.conf
            regexp: "^admin_space_left_action"
            line: "admin_space_left_action = {{ ubuntu2004cis_auditd['admin_space_left_action'] }}"
            state: present
            create: yes
        notify:
            - restart auditd

      - name: "RULE 4.1.2.3 | Ensure system is disabled when audit logs are full | space_left_action (Automated)"
        lineinfile:
            dest: /etc/audit/auditd.conf
            regexp: "^space_left_action"
            line: "space_left_action = email"
            state: present
            create: yes
        notify:
            - restart auditd

      - name: "RULE 4.1.2.3 | Ensure system is disabled when audit logs are full | action_mail_acct (Automated)"
        lineinfile:
            dest: /etc/audit/auditd.conf
            regexp: "^action_mail_acct"
            line: "action_mail_acct = root"
            state: present
            create: yes
        notify:
            - restart auditd
  when:
      - ubuntu2004cis_rule_4_1_2_3
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.2.3

- name: "RULE 4.1.3 | Ensure events that modify date and time information are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_3.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_3.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_3
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.3

- name: "RULE 4.1.4 | Ensure events that modify user/group information are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_4.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_4.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_4
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.4

- name: "RULE 4.1.5 | Ensure events that modify the system's network environment are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_5.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_5.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_5
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.5

- name: "RULE 4.1.6 | Ensure events that modify the system's Mandatory Access Controls are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_6.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_6.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_6
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.6

- name: "RULE 4.1.7 | Ensure login and logout events are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_7.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_7.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_7
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.7

- name: "RULE 4.1.8 | Ensure session initiation information is collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_8.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_8.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_8
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.8

- name: "RULE 4.1.9 | Ensure discretionary access control permission modification events are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_9.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_9.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_9
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.9

- name: "RULE 4.1.10 | Ensure unsuccessful unauthorized file access attempts are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_10.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_10.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_10
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.10

- name: "RULE 4.1.11 | Ensure use of privileged commands is collected (Automated)"
  block:

      - name: "RULE 4.1.11 | Get list of setuid/setguid binaries (Automated)"
        shell: for i in  $(df | grep '^/dev' | awk '{ print $NF }'); do find $i -xdev -type f -perm -4000 -o -type f -perm -2000 2>/dev/null; done
        register: priv_procs
        changed_when: false
        check_mode: false

      - name: "RULE 4.1.11 | Ensure use of privileged commands is collected (Automated)"
        template:
            src: audit/ubuntu2004cis_rule_4_1_11.rules.j2
            dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_11.rules
            owner: root
            group: root
            mode: 0600
        notify:
            - load audit rules
            - restart auditd
  when:
      - ubuntu2004cis_rule_4_1_11
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.11

- name: "RULE 4.1.12 | Ensure successful file system mounts are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_12.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_12.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_12
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.12

- name: "RULE 4.1.13 | Ensure file deletion events by users are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_13.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_13.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_13
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.13

- name: "RULE 4.1.14 | Ensure changes to system administration scope (sudoers) is collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_14.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_14.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_14
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.14

- name: "RULE 4.1.15 | Ensure system administrator actions (sudolog) are collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_15.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_15.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_15
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.15

- name: "RULE 4.1.16 | Ensure kernel module loading and unloading is collected (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_16.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_16.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_16
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.16

- name: "RULE 4.1.17 | Ensure the audit configuration is immutable (Automated)"
  template:
      src: audit/ubuntu2004cis_rule_4_1_17.rules.j2
      dest: /etc/audit/rules.d/ubuntu2004cis_rule_4_1_17.rules
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_4_1_17
  notify:
      - load audit rules
      - restart auditd
  tags:
      - level2
      - automated
      - patch
      - auditd
      - rule_4.1.17

- name: "RULE 4.2.1.1 | Ensure rsyslog or is installed (Automated)"
  apt:
      name: rsyslog
      state: present
      install_recommends: false
  when:
      - ubuntu2004cis_rule_4_2_1_1
      - ubuntu2004cis_syslog == "rsyslog"
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.2.1.1

- name: "RULE 4.2.1.2 | Ensure rsyslog Service is enabled (Automated)"
  service:
      name: rsyslog
      enabled: yes
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_1_2
      - ubuntu2004cis_syslog == "rsyslog"
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.2.1.2

- name: "RULE 4.2.1.3 | Ensure logging is configured (Manual)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_1_3
  tags:
      - level1
      - manual
      - patch
      - syslog
      - rule_4.2.1.3
      - notimplemented

- name: "RULE 4.2.1.4 | Ensure rsyslog default file permissions configured (Automated)"
  lineinfile:
      dest: /etc/rsyslog.conf
      regexp: '^\$FileCreateMode'
      line: '$FileCreateMode 0640'
  when:
      - ubuntu2004cis_rule_4_2_1_4
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.2.1.4

- name: "RULE 4.2.1.5 | Ensure rsyslog is configured to send logs to a remote log host (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_1_5
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.2.1.5
      - notimplemented

- name: "RULE 4.2.1.6 | Ensure remote rsyslog messages are only accepted on designated log hosts. (Manual)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_1_6
  tags:
      - level1
      - manual
      - patch
      - syslog
      - rule_4.2.1.6
      - notimplemented

- name: "RULE 4.2.2.1 | Ensure journald is configured to send logs to rsyslog (Automated)"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?ForwardToSyslog=(yes|no)"
    line: ForwardToSyslog=yes
  changed_when: false
  when:
      - ubuntu2004cis_rule_4_2_2_1
  notify:
    - restart journald
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.2.2.1

- name: "RULE 4.2.2.2 | Ensure journald is configured to compress large log files (Automated)"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?Compress=(yes|no)"
    line: Compress=yes
  when:
      - ubuntu2004cis_rule_4_2_2_2
  notify:
    - restart journald
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.2.2.2

- name: "RULE 4.2.2.3 | Ensure journald is configured to write logfiles to persistent disk (Automated)"
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "(#)?Storage=(auto|persistent)"
    line: Storage=persistent
  when:
      - ubuntu2004cis_rule_4_2_2_3
  notify:
    - restart journald
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.2.2.3

- name: "RULE 4.2.3 | Ensure permissions on all logfiles are configured (Automated)"
  command: find /var/log -type f -exec chmod g-wx,o-rwx {} +
  changed_when: false
  failed_when: false
  when:
      - ubuntu2004cis_rule_4_2_3
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.2.3

- name: "RULE 4.3 | Ensure logrotate is configured (Manual)"
  block:
      - name: "RULE 4.3 | Register logrotate.d files (Manual)"
        find:
            paths: /etc/logrotate.d/
        register: log_rotates

      - name: "RULE 4.3 | Ensure logrotate.conf exists (Manual)"
        file:
            path: /etc/logrotate.conf
            state: touch
        changed_when: false

      - name: "RULE 4.3 | Ensure logrotate is configured (Manual)"
        replace:
            path: "{{ item.path }}"
            regexp: '^(\s*)(daily|weekly|monthly|yearly)$'
            replace: "\\1{{ ubuntu2004cis_logrotate }}"
        with_items:
            - "{{ log_rotates.files }}"
            - { path: "/etc/logrotate.conf" }
  when:
      - ubuntu2004cis_rule_4_3
  tags:
      - level1
      - manual
      - patch
      - syslog
      - rule_4.3

- name: "RULE 4.4 | Ensure logrotate assigns appropriate permissions (Automated)"
  lineinfile:
      state: present
      dest: /etc/logrotate.conf
      regexp: '^create'
      line: 'create 0640'
  when:
      - ubuntu2004cis_rule_4_4
  tags:
      - level1
      - automated
      - patch
      - syslog
      - rule_4.4
