---
- name: "RULE 6.1.1 | Audit system file permissions (Manual)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_1_1
  tags:
      - level2
      - manual
      - patch
      - rule_6.1.1
      - notimplemented

- name: "RULE 6.1.2 | Ensure permissions on /etc/passwd are configured (Automated)"
  file:
      dest: /etc/passwd
      owner: root
      group: root
      mode: 0644
  when:
      - ubuntu2004cis_rule_6_1_2
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.2

- name: "RULE 6.1.3 | Ensure permissions on /etc/gshadow- are configured (Automated)"
  file:
      dest: /etc/gshadow-
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubuntu2004cis_rule_6_1_3
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.3

- name: "RULE 6.1.4 | Ensure permissions on /etc/shadow are configured (Automated)"
  file:
      dest: /etc/shadow
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubuntu2004cis_rule_6_1_4
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.4

- name: "RULE 6.1.5 | Ensure permissions on /etc/group are configured (Automated)"
  file:
      dest: /etc/group
      owner: root
      group: root
      mode: 0644
  when:
      - ubuntu2004cis_rule_6_1_5
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.5

- name: "RULE 6.1.6 | Ensure permissions on /etc/passwd- are configured (Automated)"
  file:
      dest: /etc/passwd-
      owner: root
      group: root
      mode: 0600
  when:
      - ubuntu2004cis_rule_6_1_6
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.6

- name: "RULE 6.1.7 | Ensure permissions on /etc/shadow- are configured (Automated)"
  file:
      dest: /etc/shadow-
      owner: root
      group: shadow
      mode: 0600
  when:
      - ubuntu2004cis_rule_6_1_7
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.7

- name: "RULE 6.1.8 | Ensure permissions on /etc/group- are configured (Automated)"
  file:
      dest: /etc/group-
      owner: root
      group: root
      mode: 0644
  when:
      - ubuntu2004cis_rule_6_1_8
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.8

- name: "RULE 6.1.9 | Ensure permissions on /etc/gshadow are configured (Automated)"
  file:
      dest: /etc/gshadow
      owner: root
      group: shadow
      mode: 0640
  when:
      - ubuntu2004cis_rule_6_1_9
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.9

- name: "RULE 6.1.10 | Ensure no world writable files exist (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_1_10
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.10
      - notimplemented

- name: "RULE 6.1.11 | Ensure no unowned files or directories exist (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_1_11
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.11
      - notimplemented

- name: "RULE 6.1.12 | Ensure no ungrouped files or directories exist (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_1_12
  tags:
      - level1
      - automated
      - patch
      - rule_6.1.12
      - notimplemented

- name: "RULE 6.1.13 | Audit SUID executables (Manual)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_1_13
  tags:
      - level1
      - manual
      - patch
      - rule_6.1.13
      - notimplemented

- name: "RULE 6.1.14 | Audit SGID executables (Manual)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_1_14
  tags:
      - level1
      - manual
      - patch
      - rule_6.1.14
      - notimplemented

- name: "RULE 6.2.1 | Ensure password fields are not empty (Automated)"
  command: passwd -l {{ item }}
  changed_when: false
  failed_when: false
  with_items: "{{ empty_password_accounts.stdout_lines }}"
  when:
      - empty_password_accounts.rc
      - ubuntu2004cis_rule_6_2_1
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.1

- name: "RULE 6.2.2 | Ensure root is the only UID 0 account (Automated)"
  command: passwd -l {{ item }}
  changed_when: false
  failed_when: false
  with_items: "{{ uid_zero_accounts_except_root.stdout_lines }}"
  when:
      - uid_zero_accounts_except_root.rc
      - ubuntu2004cis_rule_6_2_2
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.2

- name: "RULE 6.2.3 | Ensure root PATH Integrity (Automated)"
  block:
      - name: "RULE 6.2.3 | Ensure root PATH Integrity (unimplemented) (Automated)"
        command: /bin/true
        changed_when: false
        tags:
            - level1
            - automated
            - patch
            - rule_6.2.3
            - notimplemented

      - name: "RULE 6.2.3 | Ensure root PATH Integrity (collect paths) (Automated)"
        shell: |
          set -o pipefail;
          sudopath=($(grep secure_path /etc/sudoers | cut -f2 -d= |cut -f2 -d\"))
          IFS=:
          for i in ${sudopath[*]}
          do
            if [ -d "$i" ]
              then newsudopath+=($i)
            fi
           done
          echo "${newsudopath[*]}"
        args:
            executable: /bin/bash
        register: fixsudo
        changed_when: false
        check_mode: false
        tags:
            - level1
            - automated
            - patch
            - rule_6.2.3

      - name: "RULE 6.2.3 | Ensure root PATH Integrity (fix paths) (Automated)"
        lineinfile:
            dest: /etc/sudoers
            regexp: "(.*secure_path=).*"
            line: '\1"{{ fixsudo.stdout_lines[0] }}"'
            backrefs: true
        when:
            - fixsudo.stdout_lines[0]
        tags:
            - level1
            - automated
            - patch
            - rule_6.2.3
  when:
      - ubuntu2004cis_rule_6_2_3

- name: "RULE 6.2.4 | Ensure all users' home directories exist (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_4
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.4
      - notimplemented

- name: "RULE 6.2.5 | Ensure users' home directories permissions are 750 or more restrictive (Automated)"
  shell: |
      for dir in {{ homes_with_perms.stdout }};
      do
        chmod g-w,o-rwx $dir;
      done
  when:
      - ubuntu2004cis_rule_6_2_5
      - homes_with_perms.stdout | length > 0
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.5

- name: "RULE 6.2.6 | Ensure users own their home directories (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_6
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.6
      - notimplemented

- name: "RULE 6.2.7 | Ensure users' dot files are not group or world writable (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_7
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.7
      - notimplemented

- name: "RULE 6.2.8 | Ensure no users have .forward files (Automated)"
  file:
      state: absent
      dest: "~{{ item }}/.forward"
  with_items: "{{ users.stdout_lines }}"
  when:
      - ubuntu2004cis_rule_6_2_8
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.8

- name: "RULE 6.2.9 | Ensure no users have .netrc files (Automated)"
  file:
      state: absent
      dest: "~{{ item }}/.netrc"
  with_items: "{{ users.stdout_lines }}"
  when:
      - ubuntu2004cis_rule_6_2_9
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.9

- name: "RULE 6.2.10 | Ensure users' .netrc Files are not group or world accessible (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_10
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.10
      - notimplemented

- name: "RULE 6.2.11 | Ensure no users have .rhosts files (Automated)"
  file:
      state: absent
      dest: "~{{ item }}/.rhosts"
  with_items: "{{ users.stdout_lines }}"
  when:
      - ubuntu2004cis_rule_6_2_11
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.11

- name: "RULE 6.2.12 | Ensure all groups in /etc/passwd exist in /etc/group (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_12
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.12
      - notimplemented

- name: "RULE 6.2.13 | Ensure no duplicate UIDs exist (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_13
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.13
      - notimplemented

- name: "RULE 6.2.14 | Ensure no duplicate GIDs exist (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_14
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.14
      - notimplemented

- name: "RULE 6.2.15 | Ensure no duplicate user names exist (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_15
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.15
      - notimplemented

- name: "RULE 6.2.16 | Ensure no duplicate group names exist (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_16
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.16
      - notimplemented

- name: "RULE 6.2.17 | Ensure shadow group is empty (Automated)"
  command: /bin/true
  changed_when: false
  when:
      - ubuntu2004cis_rule_6_2_17
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.17
      - notimplemented
